const testDB = {
  MY_SECRET: "NJCMQYUAXQWOZ",
  DATABASE: "xcoins",
  DATABASE_USER: "postgres",
  DATABASE_PASSWORD: "@1/3fQT",
  SERVER_PORT: 8000,
  SECRET:
    "UTKJC_UWMCX6ASGLAIS*JHDRF$KLJGJKLFDFDQWDMCNBAMD%LKAN5LKAKLE5WLPQWPF98",
  HOST: "127.0.0.1",
  PORT: 5433,
  DIALECT: "postgres",
};

export default testDB
